<a href="https://colab.research.google.com/github/thiagolir4/Python_para_analise_de_dados_materia4_DNC/blob/main/Numpy_e_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [ ]:
import numpy as np

In [ ]:
minha_lista = [1,2,3]

In [ ]:
np.array(minha_lista)

array([1, 2, 3])

In [ ]:
minha_matriz = [[1,2,3],[4,5,6]]
print(minha_matriz)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
sum(minha_lista)

6

In [ ]:
matriz_numpy = np.array(minha_matriz)

In [ ]:
np.sum(matriz_numpy)

np.int64(21)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#dois primeiros argumentos são o range dos numeros, o terceiro é quantos numeros você quer dentro desse range
#a função gera numeros dentro desse range
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [ ]:
np.random.random(5)

array([0.01070058, 0.65390062, 0.09675344, 0.08701697, 0.68284713])

In [ ]:
np.random.random(5) * 100

array([83.79847362, 13.93777913, 76.31797454, 42.40113493, 33.64297091])

In [ ]:
np.random.random([2,5]) * 100

array([[77.44964915, 51.8251627 , 42.00667803, 97.05604111, 66.86355048],
       [71.74293957, 75.7124142 , 44.43827725, 60.80511297, 56.75871097]])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
array = np.zeros(4)

In [ ]:
array.shape

(4,)

In [ ]:
array.reshape(2,2)

array([[0., 0.],
       [0., 0.]])

In [ ]:
array_random = np.random.random(10)

In [ ]:
array_random.max()


np.float64(0.8513986760325183)

In [ ]:
array_random.min()

np.float64(0.14152126127599918)

In [ ]:
arr = np.arange(0,30,3)

In [ ]:
arr[3]

np.int64(9)

In [ ]:
arr[0:2]

array([0, 3])

In [ ]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [ ]:
arr[5:]

array([15, 18, 21, 24, 27])

In [ ]:
arr[[0,5]]

array([ 0, 15])

In [ ]:
arr[5:] = 100

In [ ]:
arr_2d = np.arange(50).reshape(5,10)

In [ ]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[0:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr_2d[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
arr_2d[0:3, 4:]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
arr_2d > 20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
np.logical_and(arr_2d > 20, arr_2d <= 30)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
booleano = np.logical_and(arr_2d > 20, arr_2d <= 30)
arr_2d[booleano]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr1 = np.arange(0,100,10)
arr2 = np.arange(0,50,5)

In [ ]:
arr1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr1 + arr2

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135])

In [ ]:
arr1 - arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr1 * arr2

array([   0,   50,  200,  450,  800, 1250, 1800, 2450, 3200, 4050])

In [ ]:
arr1 / arr2

<ipython-input-17-4b2fbeb950c1>:1: RuntimeWarning: invalid value encountered in divide
  arr1 / arr2


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [ ]:
arr1 ** arr2

array([                   1,               100000,       10240000000000,
       -2659889346031157248,  1152921504606846976,   187601812243611648,
        1152921504606846976,  2801405922193178624,                    0,
        6702376592317874176])

In [ ]:
arr1 + 100

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [ ]:
np.sqrt(arr1)

array([0.        , 3.16227766, 4.47213595, 5.47722558, 6.32455532,
       7.07106781, 7.74596669, 8.36660027, 8.94427191, 9.48683298])

#EX COM NUMPY

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(1,11)
print(f"Array de 1 a 10 {arr1}")

Array de 1 a 10 [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr_zeros = np.zeros(5)
print(f"Array de zeros {arr_zeros}")

Array de zeros [0. 0. 0. 0. 0.]


In [ ]:
arr_ones = np.ones(5)
print(f"Array de uns {arr_ones}")

Array de uns [1. 1. 1. 1. 1.]


In [ ]:
arr_linspace = np.linspace(0,50,10)
print("Linspace entre 0 e 50", arr_linspace)

Linspace entre 0 e 50 [ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [ ]:
matriz_identidade = np.eye(3)
print("Matriz identidade \n", matriz_identidade)

Matriz identidade 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr_quadrado = np.arange(1,6) ** 2
print("Quadrado do array", arr_quadrado)

Quadrado do array [ 1  4  9 16 25]


In [ ]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
arr_soma = arr_a + arr_b
print("Soma dos arrays", arr_soma)

Soma dos arrays [5 7 9]


In [ ]:
arr_reshape = np.arange(1,10).reshape(3,3)
print("Reshape do array \n", arr_reshape)

Reshape do array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr_random = np.random.rand(4,4)
print("Array random \n", arr_random)

Array random 
 [[0.9314261  0.05441206 0.75569615 0.3675607 ]
 [0.09858956 0.78493962 0.21907065 0.57926791]
 [0.17185009 0.03048949 0.04449163 0.63269249]
 [0.53602509 0.6425979  0.71903337 0.25611514]]


# PANDAS

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
minha_lista = [10,20,30]
minha_tupla = (10,20,30)
meu_array = np.array(minha_lista)
meu_dict = {"primeiro": 10, "segundo": 20, "terceiro": 30}

In [ ]:
pd.Series(data=minha_lista)

0    10
1    20
2    30
dtype: int64

In [ ]:
minha_series = pd.Series(data=minha_lista, index=["primeiro", "segundo", "terceiro"])

In [ ]:
pd.Series(data=minha_lista, index=minha_tupla)

10    10
20    20
30    30
dtype: int64

In [ ]:
minha_series[["primeiro", "terceiro"]]

primeiro    10
terceiro    30
dtype: int64

In [ ]:
#se eu nomear as chaves do dicionario com os valores da series, ele já puxa quando eu gero as series
pd.Series(meu_dict)

primeiro    10
segundo     20
terceiro    30
dtype: int64

In [ ]:
pd.Series(["a", "b", "c"])

0    a
1    b
2    c
dtype: object

In [ ]:
#sempre que tiver tipos mistos de dados, o pandas vai forçar para que todos sejam string
pd.Series([1, "a", 1.9])

0      1
1      a
2    1.9
dtype: object

In [ ]:
pd.Series([sum, min])

0    <built-in function sum>
1    <built-in function min>
dtype: object

In [ ]:
dados = np.random.rand(5,5)

In [ ]:
pd.DataFrame(dados)

0         1         2         3         4
0  0.574580  0.270711  0.938779  0.308000  0.692784
1  0.876219  0.101136  0.885015  0.259650  0.207217
2  0.825824  0.161402  0.283948  0.808751  0.524331
3  0.644121  0.792432  0.585475  0.421437  0.152970
4  0.291370  0.303387  0.148031  0.755111  0.686635

In [ ]:
pd.DataFrame(data=dados, index ="a b c d e".split())

0         1         2         3         4
a  0.574580  0.270711  0.938779  0.308000  0.692784
b  0.876219  0.101136  0.885015  0.259650  0.207217
c  0.825824  0.161402  0.283948  0.808751  0.524331
d  0.644121  0.792432  0.585475  0.421437  0.152970
e  0.291370  0.303387  0.148031  0.755111  0.686635

In [ ]:
#CRIANDO DF E NOMEANDO SEUS INDEX E COLUNAS
pd.DataFrame(data=dados, index = "a b c d e".split(), columns = "X Y Z W H".split())

X         Y         Z         W         H
a  0.574580  0.270711  0.938779  0.308000  0.692784
b  0.876219  0.101136  0.885015  0.259650  0.207217
c  0.825824  0.161402  0.283948  0.808751  0.524331
d  0.644121  0.792432  0.585475  0.421437  0.152970
e  0.291370  0.303387  0.148031  0.755111  0.686635

In [ ]:
df = pd.DataFrame(data=dados, index = "a b c d e".split(), columns = "X Y Z W H".split())

In [ ]:
#SELECIONANDO APENAS A COLONA ESPECIFICA
df["Z"]

a    0.938779
b    0.885015
c    0.283948
d    0.585475
e    0.148031
Name: Z, dtype: float64

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(df["X"])

pandas.core.series.Series

In [ ]:
#SELECIONANDO VARIAS COLUNAS
df[["X", "W"]]

X         W
a  0.574580  0.308000
b  0.876219  0.259650
c  0.825824  0.808751
d  0.644121  0.421437
e  0.291370  0.755111

In [ ]:
df.H

a    0.692784
b    0.207217
c    0.524331
d    0.152970
e    0.686635
Name: H, dtype: float64

In [ ]:
#CRIANDO NOVA COLUNA
df["new"] = [1,2,3,4,5]

In [ ]:
df

X         Y         Z         W         H  new
a  0.574580  0.270711  0.938779  0.308000  0.692784    1
b  0.876219  0.101136  0.885015  0.259650  0.207217    2
c  0.825824  0.161402  0.283948  0.808751  0.524331    3
d  0.644121  0.792432  0.585475  0.421437  0.152970    4
e  0.291370  0.303387  0.148031  0.755111  0.686635    5

In [ ]:
df["new2"] = df["X"] * df["Y"]

In [ ]:
df

X         Y         Z         W         H  new      new2
a  0.574580  0.270711  0.938779  0.308000  0.692784    1  0.155545
b  0.876219  0.101136  0.885015  0.259650  0.207217    2  0.088617
c  0.825824  0.161402  0.283948  0.808751  0.524331    3  0.133289
d  0.644121  0.792432  0.585475  0.421437  0.152970    4  0.510422
e  0.291370  0.303387  0.148031  0.755111  0.686635    5  0.088398

In [ ]:
#PEGANDO VALORES DA LINHA a
df.loc["a"]

X       0.574580
Y       0.270711
Z       0.938779
W       0.308000
H       0.692784
new     1.000000
new2    0.155545
Name: a, dtype: float64

In [ ]:
#SELECIONANDO VALORES DE DUAS LINHAS
df.loc[["a", "b"]]

X         Y         Z        W         H  new      new2
a  0.574580  0.270711  0.938779  0.30800  0.692784    1  0.155545
b  0.876219  0.101136  0.885015  0.25965  0.207217    2  0.088617

In [ ]:
#SELECIONANDO O VALOR DA LINHA a REFERENTE A COLUNA X
df.loc["a", "X"]

np.float64(0.5745803876281345)

In [ ]:
#SELECIONANDO O VALOR DA LINHA a E b REFERENTE A COLUNA X
df.loc[["a", "b"], "X"]

a    0.574580
b    0.876219
Name: X, dtype: float64

In [ ]:
#SELECIONANDO O VALOR DA LINHA a E b REFERENTE A COLUNA X e H
df.loc[["a", "b" ], ["X", "H"]]

X         H
a  0.574580  0.692784
b  0.876219  0.207217

com a função iloc eu deixo de usar o nome dos index e começo a usar como se fosse o array

In [ ]:
df.iloc[0]

X       0.574580
Y       0.270711
Z       0.938779
W       0.308000
H       0.692784
new     1.000000
new2    0.155545
Name: a, dtype: float64

In [ ]:
df.iloc[0:3]

X         Y         Z         W         H  new      new2
a  0.574580  0.270711  0.938779  0.308000  0.692784    1  0.155545
b  0.876219  0.101136  0.885015  0.259650  0.207217    2  0.088617
c  0.825824  0.161402  0.283948  0.808751  0.524331    3  0.133289

In [ ]:
df.iloc[0:3, 1]

a    0.270711
b    0.101136
c    0.161402
Name: Y, dtype: float64

In [ ]:
np.nan

nan

In [ ]:
dados = {"A": [1,2,np.nan], "B": [5,np.nan, np.nan], "C": [1,2,3]}

In [ ]:
df = pd.DataFrame(dados)

In [ ]:
df

A    B  C
0          1.0  5.0  1
1          2.0  NaN  2
2  Tá Faltando  NaN  3

In [ ]:
#remove as linhas com 2 NaN
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
#remove as colunas que tem NaN
#AXIS = 0  É LINHA
#AXIS = 1 É COLUNA
df.dropna(axis=1)

C
0  1
1  2
2  3

In [ ]:
#aqui fazemos a verificação e ele remove a coluna que tem 2 NaNs ou mais
df.dropna(thresh=2, axis=1)

A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [ ]:
df.dropna(axis=0)

A    B  C
0  1.0  5.0  1

In [ ]:
#devolve um dataframe falando onde tem um valor nulo ou não
df.isna()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
#soma por coluna, quantas celulas estão com NaN
df.isna().sum()


A    1
B    2
C    0
dtype: int64

In [ ]:
#troca os valores NaN por alguma valor determinado
df.fillna(value = "Tá faltando")

A            B  C
0          1.0          5.0  1
1          2.0  Tá faltando  2
2  Tá faltando  Tá faltando  3

In [ ]:
#troca somente os NaN da coluna A

df["A"] = df["A"].fillna(value="Tá Faltando")

In [ ]:
df

A    B  C
0          1.0  5.0  1
1          2.0  NaN  2
2  Tá Faltando  NaN  3

In [ ]:
df.fillna({"B": "Tá faltando"})

A            B  C
0          1.0          5.0  1
1          2.0  Tá faltando  2
2  Tá Faltando  Tá faltando  3

In [ ]:
df.fillna({"A": df['A'].mean(), "B": "Tá faltando"})

A            B  C
0  1.0          5.0  1
1  2.0  Tá faltando  2
2  1.5  Tá faltando  3

#GroupBy

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dados = {
    "Nome": ["Ana", "Bruno", "Carla", "Daniel", "Eduardo", "Fernanda"],
    "Departamento": ["TI", "TI", "RH","RH", "VENDAS", "VENDAS"],
    "Salario": [5000, 6000, 4000, 4200, 3000, 3500],
    "Estadao": ["SP", "RJ", "SP", "RJ", "RJ", "SP"]
}


In [ ]:
df = pd.DataFrame(dados)

In [ ]:
df

Nome Departamento  Salario Estadao
0       Ana           TI     5000      SP
1     Bruno           TI     6000      RJ
2     Carla           RH     4000      SP
3    Daniel           RH     4200      RJ
4   Eduardo       VENDAS     3000      RJ
5  Fernanda       VENDAS     3500      SP

In [ ]:
#faço o agrupamento por departamentos e depois seleciono a coluna na qual quero quero fazer as operações

df.groupby("Departamento")["Salario"].mean()

Departamento
RH        4100.0
TI        5500.0
VENDAS    3250.0
Name: Salario, dtype: float64

In [ ]:
df.groupby("Departamento")["Salario"].max()

Departamento
RH        4200
TI        6000
VENDAS    3500
Name: Salario, dtype: int64

In [ ]:
df.groupby("Departamento")["Salario"].count()

Departamento
RH        2
TI        2
VENDAS    2
Name: Salario, dtype: int64

In [ ]:
#faz a contagem de valores unicos
df.groupby("Departamento")["Salario"].nunique()

Departamento
RH        2
TI        2
VENDAS    2
Name: Salario, dtype: int64

In [ ]:
#analise agrupada das informações
df.groupby("Departamento").agg({"Salario": ["mean", "min", "max", "count", "nunique"]})

Salario                          
                mean   min   max count nunique
Departamento                                  
RH            4100.0  4000  4200     2       2
TI            5500.0  5000  6000     2       2
VENDAS        3250.0  3000  3500     2       2

In [ ]:
import pandas as pd
import numpy as np

# Criando os dataframes

usuarios_df = pd.DataFrame({
"ID_USUARIO": [1, 2, 3],
'Nome': ['Maria', 'Bruno', 'João'],
'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']
})

compras_df = pd.DataFrame({
    "ID_USUARIO": [1,2,1,1,3,3,2,3],
    "Produto": ["Notebook", "Camera", "Camiseta","Camiseta", "Caneca", "Caneca", "Calça", "Calça"],
    "Valor": [2000,1000,70,60,50,50,120,100]
})

novos_usuarios_df = pd.DataFrame({
'ID_USUARIO': [4, 5],
'Nome': ['Pedro', 'Marcos']
})

In [ ]:
usuarios_df

ID_USUARIO   Nome          Cidade
0           1  Maria       São Paulo
1           2  Bruno  Rio de Janeiro
2           3   João  Belo Horizonte

In [ ]:
compras_df

ID_USUARIO   Produto  Valor
0           1  Notebook   2000
1           2    Camera   1000
2           1  Camiseta     70
3           1  Camiseta     60
4           3    Caneca     50
5           3    Caneca     50
6           2     Calça    120
7           3     Calça    100

In [ ]:
novos_usuarios_df

ID_USUARIO    Nome
0           4   Pedro
1           5  Marcos

In [ ]:
#unindo as df usuarios e novos_usuarios
usuarios_geral = pd.concat([usuarios_df, novos_usuarios_df])

In [ ]:
usuarios_geral

ID_USUARIO    Nome          Cidade
0           1   Maria       São Paulo
1           2   Bruno  Rio de Janeiro
2           3    João  Belo Horizonte
0           4   Pedro             NaN
1           5  Marcos             NaN

In [ ]:
#atualização feita somente nessa exibição, não fica fixo no df final
usuarios_geral.fillna({"Cidade": "Cidade Não Informada"})

ID_USUARIO    Nome                Cidade
0           1   Maria             São Paulo
1           2   Bruno        Rio de Janeiro
2           3    João        Belo Horizonte
0           4   Pedro  Cidade Não Informada
1           5  Marcos  Cidade Não Informada

In [ ]:
#para alocar isso no usuario final, devemos utilizar o argumento inplace = True no final
usuarios_geral.fillna({"Cidade": "Cidade Não Informada"}, inplace=True)

In [ ]:
usuarios_geral

ID_USUARIO    Nome          Cidade
0           1   Maria       São Paulo
1           2   Bruno  Rio de Janeiro
2           3    João  Belo Horizonte
0           4   Pedro             NaN
1           5  Marcos             NaN

In [ ]:
#usando o merge
#metodos de junção
#Left => manter todos os df da esquerda e associar os valores da df da direirta
#Right => vai associar todos os dados da direita com o da esquerda
#inner => vai associar e apresentar somente os dados que tiverem relação, como no caso dos df utilizados
#ele excluiu os dois novos usuarios que n tinha compras realizada

compras_df.merge(usuarios_geral, how="left", on="ID_USUARIO" )

ID_USUARIO   Produto  Valor   Nome          Cidade
0           1  Notebook   2000  Maria       São Paulo
1           2    Camera   1000  Bruno  Rio de Janeiro
2           1  Camiseta     70  Maria       São Paulo
3           1  Camiseta     60  Maria       São Paulo
4           3    Caneca     50   João  Belo Horizonte
5           3    Caneca     50   João  Belo Horizonte
6           2     Calça    120  Bruno  Rio de Janeiro
7           3     Calça    100   João  Belo Horizonte

In [ ]:
compras_df.merge(usuarios_geral, how="right", on="ID_USUARIO" )

ID_USUARIO   Produto   Valor    Nome                Cidade
0           1  Notebook  2000.0   Maria             São Paulo
1           1  Camiseta    70.0   Maria             São Paulo
2           1  Camiseta    60.0   Maria             São Paulo
3           2    Camera  1000.0   Bruno        Rio de Janeiro
4           2     Calça   120.0   Bruno        Rio de Janeiro
5           3    Caneca    50.0    João        Belo Horizonte
6           3    Caneca    50.0    João        Belo Horizonte
7           3     Calça   100.0    João        Belo Horizonte
8           4       NaN     NaN   Pedro  Cidade Não Informada
9           5       NaN     NaN  Marcos  Cidade Não Informada

In [ ]:
compras_df.merge(usuarios_geral, how="inner", on="ID_USUARIO" )

ID_USUARIO   Produto  Valor   Nome          Cidade
0           1  Notebook   2000  Maria       São Paulo
1           2    Camera   1000  Bruno  Rio de Janeiro
2           1  Camiseta     70  Maria       São Paulo
3           1  Camiseta     60  Maria       São Paulo
4           3    Caneca     50   João  Belo Horizonte
5           3    Caneca     50   João  Belo Horizonte
6           2     Calça    120  Bruno  Rio de Janeiro
7           3     Calça    100   João  Belo Horizonte

#OUTRAS OPERAÇÕES


In [ ]:
import pandas as pd
import numpy as np
compras = {
'ID_usuario': [1, 2, 1, 1, 3, 3, 2, 3],
'Produto': ['notebook', 'camera', 'camiseta', 'camiseta', 'caneca', 'caneca', 'calça', 'calça'],
'Valor': [2000, 1000, 70, 60, 50, 50, 120, 100]
}

In [ ]:
df = pd.DataFrame(compras)

In [ ]:
df

ID_usuario   Produto  Valor
0           1  notebook   2000
1           2    camera   1000
2           1  camiseta     70
3           1  camiseta     60
4           3    caneca     50
5           3    caneca     50
6           2     calça    120
7           3     calça    100

In [ ]:
#a função head diminui a exibição ref ao valor do parametro passado
df.head(2)

ID_usuario   Produto  Valor
0           1  notebook   2000
1           2    camera   1000

In [ ]:
#a função tail faz ao contrario do head e me mostra de baixo para cima
df.tail(2)

ID_usuario Produto  Valor
6           2   calça    120
7           3   calça    100

In [ ]:
df["Produto"]

0    notebook
1      camera
2    camiseta
3    camiseta
4      caneca
5      caneca
6       calça
7       calça
Name: Produto, dtype: object

In [ ]:
#a função unique me mostra os valores unicos na coluna
df["Produto"].unique()

array(['notebook', 'camera', 'camiseta', 'caneca', 'calça'], dtype=object)

In [ ]:
#me devolvea quantidade de itens unicos na coluna
df["Produto"].nunique()

#ou poderia usar o len da segunite forma = len(df["Produto"].unique())
#teria o mesmo retorno

5

In [ ]:
#contar quantos casos existem por produto comprado
df.groupby("Produto")["ID_usuario"].count()

Produto
calça       2
camera      1
camiseta    2
caneca      2
notebook    1
Name: ID_usuario, dtype: int64

In [ ]:
df["Produto"].value_counts()

Produto
camiseta    2
calça       2
caneca      2
notebook    1
camera      1
Name: count, dtype: int64

In [ ]:
df["Valor"]/100

0    20.0
1    10.0
2     0.7
3     0.6
4     0.5
5     0.5
6     1.2
7     1.0
Name: Valor, dtype: float64

In [ ]:
def valor_agregado(valor):
  if valor >= 1000:
    return "Alto Valor"
  else:
    return "Baixo Valor"



In [ ]:
#a função apply permite que a aplicação de funções externas em colunas dos nossos df
df["Valor"].apply(valor_agregado)

0     Alto Valor
1     Alto Valor
2    Baixo Valor
3    Baixo Valor
4    Baixo Valor
5    Baixo Valor
6    Baixo Valor
7    Baixo Valor
Name: Valor, dtype: object

In [ ]:
#fazendo com que o retorno da função anterior comece a fazer parte do nosso df
df["Valor Agregado"]=df["Valor"].apply(valor_agregado)

In [ ]:
df

ID_usuario   Produto  Valor Valor Agregado
0           1  notebook   2000     Alto Valor
1           2    camera   1000     Alto Valor
2           1  camiseta     70    Baixo Valor
3           1  camiseta     60    Baixo Valor
4           3    caneca     50    Baixo Valor
5           3    caneca     50    Baixo Valor
6           2     calça    120    Baixo Valor
7           3     calça    100    Baixo Valor

In [ ]:
#def substitui(nome_produto):
 # if nome_produto == "notebook":
  #  return "computador"
  #else:
   # return nome_produto


In [ ]:
#df["Produto"].apply(substitui)

0    computador
1        camera
2      camiseta
3      camiseta
4        caneca
5        caneca
6         calça
7         calça
Name: Produto, dtype: object

In [ ]:
#fazendo o mesmo codigo acima, com funções lambd
df["Produto"].apply(lambda nome_produto: "computador" if nome_produto == "notebook" else nome_produto)

0    computador
1        camera
2      camiseta
3      camiseta
4        caneca
5        caneca
6         calça
7         calça
Name: Produto, dtype: object

In [ ]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [ ]:
df.columns

Index(['ID_usuario', 'Produto', 'Valor', 'Valor Agregado'], dtype='object')

In [ ]:
df.sort_values(by="Valor")

ID_usuario   Produto  Valor Valor Agregado
5           3    caneca     50    Baixo Valor
4           3    caneca     50    Baixo Valor
3           1  camiseta     60    Baixo Valor
2           1  camiseta     70    Baixo Valor
7           3     calça    100    Baixo Valor
6           2     calça    120    Baixo Valor
1           2    camera   1000     Alto Valor
0           1  notebook   2000     Alto Valor

In [ ]:
#para inverter a ordenação e colocar de forma decrescente
df.sort_values(by="Valor", ascending=False)

ID_usuario   Produto  Valor Valor Agregado
0           1  notebook   2000     Alto Valor
1           2    camera   1000     Alto Valor
6           2     calça    120    Baixo Valor
7           3     calça    100    Baixo Valor
2           1  camiseta     70    Baixo Valor
3           1  camiseta     60    Baixo Valor
5           3    caneca     50    Baixo Valor
4           3    caneca     50    Baixo Valor

#USANDO ENTRADAS E SAIDA DE DADOS

In [ ]:
import pandas as pd

In [ ]:
#função para leitura do arquivo, primeiro o nome do arquivo e depois o separador
df = pd.read_csv("testecsv.csv", sep= ",")

In [ ]:
df

Data  Produto  Quantidade  PrecoUnitario  Total
0  2025-01-01   Camisa           2           50.0  100.0
1  2025-01-01    Calça           1          120.0  120.0
2  2025-01-02    Tênis           1          200.0  200.0
3  2025-01-03   Camisa           3           50.0  150.0
4  2025-01-03  Bermuda           2           80.0  160.0
5  2025-01-04    Tênis           2          200.0  400.0

In [ ]:
#quantidade de linhas
len(df)

6

In [ ]:
#linhas e colunas
df.shape

(6, 5)

In [ ]:
#conta quantidade de linhas por coluna
df.count()

Data             6
Produto          6
Quantidade       6
PrecoUnitario    6
Total            6
dtype: int64

In [ ]:
#no exemplo em aula estamos usando uma planilha de dados do spotify
#o codigo abaixo remote as duplicados
#df_albums = df[["artist_name, "album_name]].drop_duplicates()

In [ ]:
#salvando como csv
df.to_csv("csvtratado.csv", sep=",")

In [ ]:
df.to_excel("exceltratado.xlsx")

In [ ]:
df2  =pd.read_excel("exceltratado.xlsx")

In [ ]:
df2

Unnamed: 0        Data  Produto  Quantidade  PrecoUnitario  Total
0           0  2025-01-01   Camisa           2             50    100
1           1  2025-01-01    Calça           1            120    120
2           2  2025-01-02    Tênis           1            200    200
3           3  2025-01-03   Camisa           3             50    150
4           4  2025-01-03  Bermuda           2             80    160
5           5  2025-01-04    Tênis           2            200    400

In [ ]:
#removendo coluna unnamed
df2.drop(columns="Unnamed: 0", inplace=True)

In [ ]:
df2

Data  Produto  Quantidade  PrecoUnitario  Total
0  2025-01-01   Camisa           2             50    100
1  2025-01-01    Calça           1            120    120
2  2025-01-02    Tênis           1            200    200
3  2025-01-03   Camisa           3             50    150
4  2025-01-03  Bermuda           2             80    160
5  2025-01-04    Tênis           2            200    400

#EXERCICIOS PANDAS

In [6]:
import pandas as pd

In [8]:
df = pd.read_csv("Salaries.csv", sep=",")

<ipython-input-8-541ebbddb1a4>:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Salaries.csv", sep=",")


In [ ]:
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43   
1          245131.88     137811.38           NaN  538909.28         538909.28   
2          106088.18       16452.6           NaN  335279.91         335279.91   
3           56120.71      198306.9           NaN  332343.61         332343.61   
4             9737.0     182234.59           NaN  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [ ]:
#exibindo as 5 primeiras linhas
df.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [ ]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [ ]:
#mostrando todas as infomações do df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


descubra a quantidade de dados

In [ ]:
df.count()

Id                  148654
EmployeeName        148654
JobTitle            148654
BasePay             148049
OvertimePay         148654
OtherPay            148654
Benefits            112495
TotalPay            148654
TotalPayBenefits    148654
Year                148654
Notes                    0
Agency              148654
Status               38119
dtype: int64

In [ ]:
len(df)

148654

qual é a BasePay médio?

In [36]:
df["BasePay"]

0         167411.18
1         155966.02
2         212739.13
3          77916.00
4         134401.60
            ...    
116470     94191.00
116471    114313.80
116472    118898.10
116473     94355.00
116474         9.00
Name: BasePay, Length: 116475, dtype: float64

In [37]:
df[df["BasePay"]=="Not Provided"]

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

In [ ]:
#salvando o df sem as informações not provided
df = df[~(df["BasePay"]=="Not Provided")]

In [38]:
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
116470  116471    Enrique O Mixco   
116471  116472      Kelly L Swift   
116472  116473    Dennis E Cesena   
116473  116474   Jeffrey H Bishop   
116474  116475  Ramon R Dominguez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
116470                                  Deputy Sheriff   94191.00   
116471                                Registered Nurse  114313.80   
116472                                Police Officer 3  118898.10   
116473                                     Electrician   94355.00   
116474                          Construction Inspector       9.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits    Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011.0   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011.0   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011.0   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011.0   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011.0   
...             ...        ...       ...        ...               ...     ...   
116470     20838.73   16240.60  37252.95  131270.33         168523.28  2014.0   
116471     10970.38    6405.62  36832.68  131689.80         168522.48  2014.0   
116472      7079.25    3697.68  38839.63  129675.03         168514.66  2014.0   
116473     38331.68       0.00  35811.20  132686.68         168497.88  2014.0   
116474          NaN        NaN       NaN        NaN               NaN     NaN   

        Notes         Agency Status  
0         NaN  San Francisco    NaN  
1         NaN  San Francisco    NaN  
2         NaN  San Francisco    NaN  
3         NaN  San Francisco    NaN  
4         NaN  San Francisco    NaN  
...       ...            ...    ...  
116470    NaN  San Francisco     FT  
116471    NaN  San Francisco     PT  
116472    NaN  San Francisco     FT  
116473    NaN  San Francisco     FT  
116474    NaN            NaN    NaN  

[116475 rows x 13 columns]

In [ ]:
df["BasePay"].dtype

dtype('O')

In [ ]:
#convertendo a coluna para float para realizar operações com ela
df["BasePay"] = df["BasePay"].astype(float)

<ipython-input-114-075938fdc0eb>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["BasePay"] = df["BasePay"].astype(float)


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148650 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148650 non-null  int64  
 1   EmployeeName      148650 non-null  object 
 2   JobTitle          148650 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  object 
 5   OtherPay          148650 non-null  object 
 6   Benefits          112491 non-null  object 
 7   TotalPay          148650 non-null  float64
 8   TotalPayBenefits  148650 non-null  float64
 9   Year              148650 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148650 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(4), int64(2), object(7)
memory usage: 15.9+ MB


In [ ]:
#media da coluna BasePay
df["BasePay"].mean()

np.float64(66325.4488404877)

Qual é o maior OvertimePay do dataset

In [ ]:
df["OvertimePay"].astype(float).max()

245131.88

In [ ]:
#mostrando as informações da pessoa com maior pagamento
df[df["OvertimePay"]==df["OvertimePay"].astype(float).max()]

Id  EmployeeName                         JobTitle    BasePay OvertimePay  \
1   2  GARY JIMENEZ  CAPTAIN III (POLICE DEPARTMENT)  155966.02   245131.88   

    OtherPay Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
1  137811.38      NaN  538909.28         538909.28  2011    NaN   

          Agency Status  
1  San Francisco    NaN

Qual o cargo de Joseph Driscall?

In [9]:
df[df["EmployeeName"]== "JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

Quanto ele ganha com beneficios?

In [10]:
df[df["EmployeeName"]== "JOSEPH DRISCOLL"]["TotalPay"]

24    270324.91
Name: TotalPay, dtype: float64

Quem é a pessoal que tem o maior salario base?

In [12]:
df['BasePay'].max()

319275.01

In [13]:
df[df["BasePay"]== df["BasePay"].max()]

Id    EmployeeName         JobTitle    BasePay  OvertimePay  \
72925  72926  Gregory P Suhr  Chief of Police  319275.01          0.0   

       OtherPay  Benefits   TotalPay  TotalPayBenefits    Year  Notes  \
72925  20007.06  86533.21  339282.07         425815.28  2013.0    NaN   

              Agency Status  
72925  San Francisco    NaN

Quem é a pessoa mais mal paga?


In [14]:
df['BasePay'].min()

-166.01

In [19]:
df[df["BasePay"]==df["BasePay"].min()]

Id    EmployeeName      JobTitle  BasePay  OvertimePay  OtherPay  \
72832  72833  Irwin Sidharta  Junior Clerk  -166.01       249.02       0.0   

       Benefits  TotalPay  TotalPayBenefits    Year  Notes         Agency  \
72832      6.56     83.01             89.57  2012.0    NaN  San Francisco   

      Status  
72832    NaN

Qual é a media salarial por ano?

In [21]:
df["Year"].value_counts()

Year
2013.0    37606
2012.0    36766
2011.0    36159
2014.0     5943
Name: count, dtype: int64

In [24]:
df.groupby("Year").agg({"BasePay": ["mean"]})

BasePay
                 mean
Year                 
2011.0   63595.956517
2012.0   65436.406857
2013.0   69630.030216
2014.0  133851.629618

Quantos tipos de trabalho existem?

In [25]:
df["JobTitle"].nunique()

2129

Quais são os cinco principais empregos mais comuns?

In [30]:
df["JobTitle"].value_counts()

JobTitle
Transit Operator                                      4564
Registered Nurse                                      3058
Special Nurse                                         2915
TRANSIT OPERATOR                                      2388
Police Officer 3                                      2171
                                                      ... 
CITY ATTORNEY                                            1
CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC SAFE       1
WIRE ROPE CABLE MAINTENANCE SUPERVISOR                   1
Water Meter Shop Supervisor 1                            1
Undersheriff (SFERS)                                     1
Name: count, Length: 2129, dtype: int64

Quantas pessoas tem a palavra chefe no nome do cargo?

In [32]:
def chefe(valor):
  if "chief" in valor.lower():
    return True
  else:
    return False

In [34]:
df["JobTitle"].apply(chefe)

0         False
1         False
2         False
3         False
4          True
          ...  
116470    False
116471    False
116472    False
116473    False
116474    False
Name: JobTitle, Length: 116475, dtype: bool

In [35]:
df[df["JobTitle"].apply(chefe)]

Id        EmployeeName  \
4            5     PATRICK GARDNER   
5            6      DAVID SULLIVAN   
6            7           ALSON LEE   
8            9      MICHAEL MORRIS   
9           10  JOANNE HAYES-WHITE   
...        ...                 ...   
114750  114751        Ronald K Tom   
114950  114951      Anthony Grieco   
115298  115299         Ron H Allen   
115692  115693     Perry J Bonelli   
116422  116423        Jimmy L Kirk   

                                            JobTitle    BasePay  OvertimePay  \
4       DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   
5                          ASSISTANT DEPUTY CHIEF II  118602.00      8601.00   
6                 BATTALION CHIEF, (FIRE DEPARTMENT)   92492.01     89062.90   
8                 BATTALION CHIEF, (FIRE DEPARTMENT)  176932.64     86362.68   
9             CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  285262.00         0.00   
...                                              ...        ...          ...   
114750                      Chief Building Inspector  132690.00         0.00   
114950                      Chief Building Inspector  131423.96         0.00   
115298                    Chief Electrical Inspector  132690.08         0.00   
115692                     Chief Stationary Engineer   99736.02     31867.55   
116422                     Chief Stationary Engineer   99736.00      6241.81   

         OtherPay  Benefits   TotalPay  TotalPayBenefits    Year  Notes  \
4       182234.59       NaN  326373.19         326373.19  2011.0    NaN   
5       189082.74       NaN  316285.74         316285.74  2011.0    NaN   
6       134426.14       NaN  315981.05         315981.05  2011.0    NaN   
8        40132.23       NaN  303427.55         303427.55  2011.0    NaN   
9        17115.73       NaN  302377.73         302377.73  2011.0    NaN   
...           ...       ...        ...               ...     ...    ...   
114750    6634.50  43621.83  139324.50         182946.33  2014.0    NaN   
114950    6571.22  43211.78  137995.18         181206.96  2014.0    NaN   
115298    2653.80  42771.59  135343.88         178115.47  2014.0    NaN   
115692    5934.50  36955.11  137538.07         174493.18  2014.0    NaN   
116422   25945.82  36957.70  131923.63         168881.33  2014.0    NaN   

               Agency Status  
4       San Francisco    NaN  
5       San Francisco    NaN  
6       San Francisco    NaN  
8       San Francisco    NaN  
9       San Francisco    NaN  
...               ...    ...  
114750  San Francisco     FT  
114950  San Francisco     FT  
115298  San Francisco     FT  
115692  San Francisco     FT  
116422  San Francisco     FT  

[579 rows x 13 columns]