<a href="https://colab.research.google.com/github/thiagolir4/Python_para_analise_de_dados_materia4_DNC/blob/main/Python_para_analise_de_dados_materia4_DNC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [ ]:
import numpy as np

In [ ]:
minha_lista = [1,2,3]

In [ ]:
np.array(minha_lista)

array([1, 2, 3])

In [ ]:
minha_matriz = [[1,2,3],[4,5,6]]
print(minha_matriz)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
sum(minha_lista)

6

In [ ]:
matriz_numpy = np.array(minha_matriz)

In [ ]:
np.sum(matriz_numpy)

np.int64(21)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#dois primeiros argumentos são o range dos numeros, o terceiro é quantos numeros você quer dentro desse range
#a função gera numeros dentro desse range
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [ ]:
np.random.random(5)

array([0.01070058, 0.65390062, 0.09675344, 0.08701697, 0.68284713])

In [ ]:
np.random.random(5) * 100

array([83.79847362, 13.93777913, 76.31797454, 42.40113493, 33.64297091])

In [ ]:
np.random.random([2,5]) * 100

array([[77.44964915, 51.8251627 , 42.00667803, 97.05604111, 66.86355048],
       [71.74293957, 75.7124142 , 44.43827725, 60.80511297, 56.75871097]])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
array = np.zeros(4)

In [ ]:
array.shape

(4,)

In [ ]:
array.reshape(2,2)

array([[0., 0.],
       [0., 0.]])

In [ ]:
array_random = np.random.random(10)

In [ ]:
array_random.max()


np.float64(0.8513986760325183)

In [ ]:
array_random.min()

np.float64(0.14152126127599918)

In [ ]:
arr = np.arange(0,30,3)

In [ ]:
arr[3]

np.int64(9)

In [ ]:
arr[0:2]

array([0, 3])

In [ ]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [ ]:
arr[5:]

array([15, 18, 21, 24, 27])

In [ ]:
arr[[0,5]]

array([ 0, 15])

In [ ]:
arr[5:] = 100

In [ ]:
arr_2d = np.arange(50).reshape(5,10)

In [ ]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[0:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr_2d[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
arr_2d[0:3, 4:]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
arr_2d > 20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
np.logical_and(arr_2d > 20, arr_2d <= 30)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
booleano = np.logical_and(arr_2d > 20, arr_2d <= 30)
arr_2d[booleano]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr1 = np.arange(0,100,10)
arr2 = np.arange(0,50,5)

In [ ]:
arr1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr1 + arr2

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135])

In [ ]:
arr1 - arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr1 * arr2

array([   0,   50,  200,  450,  800, 1250, 1800, 2450, 3200, 4050])

In [ ]:
arr1 / arr2

<ipython-input-17-4b2fbeb950c1>:1: RuntimeWarning: invalid value encountered in divide
  arr1 / arr2


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [ ]:
arr1 ** arr2

array([                   1,               100000,       10240000000000,
       -2659889346031157248,  1152921504606846976,   187601812243611648,
        1152921504606846976,  2801405922193178624,                    0,
        6702376592317874176])

In [ ]:
arr1 + 100

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [ ]:
np.sqrt(arr1)

array([0.        , 3.16227766, 4.47213595, 5.47722558, 6.32455532,
       7.07106781, 7.74596669, 8.36660027, 8.94427191, 9.48683298])

#EX COM NUMPY

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(1,11)
print(f"Array de 1 a 10 {arr1}")

Array de 1 a 10 [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr_zeros = np.zeros(5)
print(f"Array de zeros {arr_zeros}")

Array de zeros [0. 0. 0. 0. 0.]


In [ ]:
arr_ones = np.ones(5)
print(f"Array de uns {arr_ones}")

Array de uns [1. 1. 1. 1. 1.]


In [ ]:
arr_linspace = np.linspace(0,50,10)
print("Linspace entre 0 e 50", arr_linspace)

Linspace entre 0 e 50 [ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [ ]:
matriz_identidade = np.eye(3)
print("Matriz identidade \n", matriz_identidade)

Matriz identidade 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr_quadrado = np.arange(1,6) ** 2
print("Quadrado do array", arr_quadrado)

Quadrado do array [ 1  4  9 16 25]


In [ ]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
arr_soma = arr_a + arr_b
print("Soma dos arrays", arr_soma)

Soma dos arrays [5 7 9]


In [ ]:
arr_reshape = np.arange(1,10).reshape(3,3)
print("Reshape do array \n", arr_reshape)

Reshape do array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr_random = np.random.rand(4,4)
print("Array random \n", arr_random)

Array random 
 [[0.9314261  0.05441206 0.75569615 0.3675607 ]
 [0.09858956 0.78493962 0.21907065 0.57926791]
 [0.17185009 0.03048949 0.04449163 0.63269249]
 [0.53602509 0.6425979  0.71903337 0.25611514]]


# PANDAS

In [2]:
import pandas as pd
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
minha_lista = [10,20,30]
minha_tupla = (10,20,30)
meu_array = np.array(minha_lista)
meu_dict = {"primeiro": 10, "segundo": 20, "terceiro": 30}

In [ ]:
pd.Series(data=minha_lista)

0    10
1    20
2    30
dtype: int64

In [ ]:
minha_series = pd.Series(data=minha_lista, index=["primeiro", "segundo", "terceiro"])

In [ ]:
pd.Series(data=minha_lista, index=minha_tupla)

10    10
20    20
30    30
dtype: int64

In [ ]:
minha_series[["primeiro", "terceiro"]]

primeiro    10
terceiro    30
dtype: int64

In [ ]:
#se eu nomear as chaves do dicionario com os valores da series, ele já puxa quando eu gero as series
pd.Series(meu_dict)

primeiro    10
segundo     20
terceiro    30
dtype: int64

In [ ]:
pd.Series(["a", "b", "c"])

0    a
1    b
2    c
dtype: object

In [ ]:
#sempre que tiver tipos mistos de dados, o pandas vai forçar para que todos sejam string
pd.Series([1, "a", 1.9])

0      1
1      a
2    1.9
dtype: object

In [ ]:
pd.Series([sum, min])

0    <built-in function sum>
1    <built-in function min>
dtype: object

In [ ]:
dados = np.random.rand(5,5)

In [ ]:
pd.DataFrame(dados)

0         1         2         3         4
0  0.574580  0.270711  0.938779  0.308000  0.692784
1  0.876219  0.101136  0.885015  0.259650  0.207217
2  0.825824  0.161402  0.283948  0.808751  0.524331
3  0.644121  0.792432  0.585475  0.421437  0.152970
4  0.291370  0.303387  0.148031  0.755111  0.686635

In [ ]:
pd.DataFrame(data=dados, index ="a b c d e".split())

0         1         2         3         4
a  0.574580  0.270711  0.938779  0.308000  0.692784
b  0.876219  0.101136  0.885015  0.259650  0.207217
c  0.825824  0.161402  0.283948  0.808751  0.524331
d  0.644121  0.792432  0.585475  0.421437  0.152970
e  0.291370  0.303387  0.148031  0.755111  0.686635

In [ ]:
#CRIANDO DF E NOMEANDO SEUS INDEX E COLUNAS
pd.DataFrame(data=dados, index = "a b c d e".split(), columns = "X Y Z W H".split())

X         Y         Z         W         H
a  0.574580  0.270711  0.938779  0.308000  0.692784
b  0.876219  0.101136  0.885015  0.259650  0.207217
c  0.825824  0.161402  0.283948  0.808751  0.524331
d  0.644121  0.792432  0.585475  0.421437  0.152970
e  0.291370  0.303387  0.148031  0.755111  0.686635

In [ ]:
df = pd.DataFrame(data=dados, index = "a b c d e".split(), columns = "X Y Z W H".split())

In [ ]:
#SELECIONANDO APENAS A COLONA ESPECIFICA
df["Z"]

a    0.938779
b    0.885015
c    0.283948
d    0.585475
e    0.148031
Name: Z, dtype: float64

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(df["X"])

pandas.core.series.Series

In [ ]:
#SELECIONANDO VARIAS COLUNAS
df[["X", "W"]]

X         W
a  0.574580  0.308000
b  0.876219  0.259650
c  0.825824  0.808751
d  0.644121  0.421437
e  0.291370  0.755111

In [ ]:
df.H

a    0.692784
b    0.207217
c    0.524331
d    0.152970
e    0.686635
Name: H, dtype: float64

In [ ]:
#CRIANDO NOVA COLUNA
df["new"] = [1,2,3,4,5]

In [ ]:
df

X         Y         Z         W         H  new
a  0.574580  0.270711  0.938779  0.308000  0.692784    1
b  0.876219  0.101136  0.885015  0.259650  0.207217    2
c  0.825824  0.161402  0.283948  0.808751  0.524331    3
d  0.644121  0.792432  0.585475  0.421437  0.152970    4
e  0.291370  0.303387  0.148031  0.755111  0.686635    5

In [ ]:
df["new2"] = df["X"] * df["Y"]

In [ ]:
df

X         Y         Z         W         H  new      new2
a  0.574580  0.270711  0.938779  0.308000  0.692784    1  0.155545
b  0.876219  0.101136  0.885015  0.259650  0.207217    2  0.088617
c  0.825824  0.161402  0.283948  0.808751  0.524331    3  0.133289
d  0.644121  0.792432  0.585475  0.421437  0.152970    4  0.510422
e  0.291370  0.303387  0.148031  0.755111  0.686635    5  0.088398

In [ ]:
#PEGANDO VALORES DA LINHA a
df.loc["a"]

X       0.574580
Y       0.270711
Z       0.938779
W       0.308000
H       0.692784
new     1.000000
new2    0.155545
Name: a, dtype: float64

In [ ]:
#SELECIONANDO VALORES DE DUAS LINHAS
df.loc[["a", "b"]]

X         Y         Z        W         H  new      new2
a  0.574580  0.270711  0.938779  0.30800  0.692784    1  0.155545
b  0.876219  0.101136  0.885015  0.25965  0.207217    2  0.088617

In [ ]:
#SELECIONANDO O VALOR DA LINHA a REFERENTE A COLUNA X
df.loc["a", "X"]

np.float64(0.5745803876281345)

In [ ]:
#SELECIONANDO O VALOR DA LINHA a E b REFERENTE A COLUNA X
df.loc[["a", "b"], "X"]

a    0.574580
b    0.876219
Name: X, dtype: float64

In [ ]:
#SELECIONANDO O VALOR DA LINHA a E b REFERENTE A COLUNA X e H
df.loc[["a", "b" ], ["X", "H"]]

X         H
a  0.574580  0.692784
b  0.876219  0.207217

com a função iloc eu deixo de usar o nome dos index e começo a usar como se fosse o array

In [ ]:
df.iloc[0]

X       0.574580
Y       0.270711
Z       0.938779
W       0.308000
H       0.692784
new     1.000000
new2    0.155545
Name: a, dtype: float64

In [ ]:
df.iloc[0:3]

X         Y         Z         W         H  new      new2
a  0.574580  0.270711  0.938779  0.308000  0.692784    1  0.155545
b  0.876219  0.101136  0.885015  0.259650  0.207217    2  0.088617
c  0.825824  0.161402  0.283948  0.808751  0.524331    3  0.133289

In [ ]:
df.iloc[0:3, 1]

a    0.270711
b    0.101136
c    0.161402
Name: Y, dtype: float64

In [3]:
np.nan

nan

In [31]:
dados = {"A": [1,2,np.nan], "B": [5,np.nan, np.nan], "C": [1,2,3]}

In [30]:
df = pd.DataFrame(dados)

In [29]:
df

A    B  C
0          1.0  5.0  1
1          2.0  NaN  2
2  Tá Faltando  NaN  3

In [8]:
#remove as linhas com 2 NaN
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [10]:
#remove as colunas que tem NaN
#AXIS = 0  É LINHA
#AXIS = 1 É COLUNA
df.dropna(axis=1)

C
0  1
1  2
2  3

In [11]:
#aqui fazemos a verificação e ele remove a coluna que tem 2 NaNs ou mais
df.dropna(thresh=2, axis=1)

A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [12]:
df.dropna(axis=0)

A    B  C
0  1.0  5.0  1

In [17]:
#devolve um dataframe falando onde tem um valor nulo ou não
df.isna()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [18]:
#soma por coluna, quantas celulas estão com NaN
df.isna().sum()


A    1
B    2
C    0
dtype: int64

In [19]:
#troca os valores NaN por alguma valor determinado
df.fillna(value = "Tá faltando")

A            B  C
0          1.0          5.0  1
1          2.0  Tá faltando  2
2  Tá faltando  Tá faltando  3

In [20]:
#troca somente os NaN da coluna A

df["A"] = df["A"].fillna(value="Tá Faltando")

In [21]:
df

A    B  C
0          1.0  5.0  1
1          2.0  NaN  2
2  Tá Faltando  NaN  3

In [22]:
df.fillna({"B": "Tá faltando"})

A            B  C
0          1.0          5.0  1
1          2.0  Tá faltando  2
2  Tá Faltando  Tá faltando  3

In [33]:
df.fillna({"A": df['A'].mean(), "B": "Tá faltando"})

A            B  C
0  1.0          5.0  1
1  2.0  Tá faltando  2
2  1.5  Tá faltando  3