<a href="https://colab.research.google.com/github/thiagolir4/Python_para_analise_de_dados_materia4_DNC/blob/main/Python_para_analise_de_dados_materia4_DNC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [2]:
import numpy as np

In [9]:
minha_lista = [1,2,3]

In [10]:
np.array(minha_lista)

array([1, 2, 3])

In [ ]:
minha_matriz = [[1,2,3],[4,5,6]]
print(minha_matriz)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
sum(minha_lista)

6

In [ ]:
matriz_numpy = np.array(minha_matriz)

In [ ]:
np.sum(matriz_numpy)

np.int64(21)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#dois primeiros argumentos são o range dos numeros, o terceiro é quantos numeros você quer dentro desse range
#a função gera numeros dentro desse range
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [ ]:
np.random.random(5)

array([0.01070058, 0.65390062, 0.09675344, 0.08701697, 0.68284713])

In [ ]:
np.random.random(5) * 100

array([83.79847362, 13.93777913, 76.31797454, 42.40113493, 33.64297091])

In [ ]:
np.random.random([2,5]) * 100

array([[77.44964915, 51.8251627 , 42.00667803, 97.05604111, 66.86355048],
       [71.74293957, 75.7124142 , 44.43827725, 60.80511297, 56.75871097]])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
array = np.zeros(4)

In [ ]:
array.shape

(4,)

In [ ]:
array.reshape(2,2)

array([[0., 0.],
       [0., 0.]])

In [ ]:
array_random = np.random.random(10)

In [ ]:
array_random.max()


np.float64(0.8513986760325183)

In [ ]:
array_random.min()

np.float64(0.14152126127599918)

In [ ]:
arr = np.arange(0,30,3)

In [ ]:
arr[3]

np.int64(9)

In [ ]:
arr[0:2]

array([0, 3])

In [ ]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [ ]:
arr[5:]

array([15, 18, 21, 24, 27])

In [ ]:
arr[[0,5]]

array([ 0, 15])

In [ ]:
arr[5:] = 100

In [ ]:
arr_2d = np.arange(50).reshape(5,10)

In [ ]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[0:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
arr_2d[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
arr_2d[0:3, 4:]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
arr_2d > 20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
np.logical_and(arr_2d > 20, arr_2d <= 30)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
booleano = np.logical_and(arr_2d > 20, arr_2d <= 30)
arr_2d[booleano]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [7]:
arr1 = np.arange(0,100,10)
arr2 = np.arange(0,50,5)

In [13]:
arr1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
arr1 + arr2

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135])

In [15]:
arr1 - arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
arr1 * arr2

array([   0,   50,  200,  450,  800, 1250, 1800, 2450, 3200, 4050])

In [17]:
arr1 / arr2

<ipython-input-17-4b2fbeb950c1>:1: RuntimeWarning: invalid value encountered in divide
  arr1 / arr2


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [18]:
arr1 ** arr2

array([                   1,               100000,       10240000000000,
       -2659889346031157248,  1152921504606846976,   187601812243611648,
        1152921504606846976,  2801405922193178624,                    0,
        6702376592317874176])

In [19]:
arr1 + 100

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [20]:
np.sqrt(arr1)

array([0.        , 3.16227766, 4.47213595, 5.47722558, 6.32455532,
       7.07106781, 7.74596669, 8.36660027, 8.94427191, 9.48683298])

#EX COM NUMPY

In [21]:
import numpy as np

In [22]:
arr1 = np.arange(1,11)
print(f"Array de 1 a 10 {arr1}")

Array de 1 a 10 [ 1  2  3  4  5  6  7  8  9 10]


In [23]:
arr_zeros = np.zeros(5)
print(f"Array de zeros {arr_zeros}")

Array de zeros [0. 0. 0. 0. 0.]


In [24]:
arr_ones = np.ones(5)
print(f"Array de uns {arr_ones}")

Array de uns [1. 1. 1. 1. 1.]


In [26]:
arr_linspace = np.linspace(0,50,10)
print("Linspace entre 0 e 50", arr_linspace)

Linspace entre 0 e 50 [ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [28]:
matriz_identidade = np.eye(3)
print("Matriz identidade \n", matriz_identidade)

Matriz identidade 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
arr_quadrado = np.arange(1,6) ** 2
print("Quadrado do array", arr_quadrado)

Quadrado do array [ 1  4  9 16 25]


In [33]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
arr_soma = arr_a + arr_b
print("Soma dos arrays", arr_soma)

Soma dos arrays [5 7 9]


In [35]:
arr_reshape = np.arange(1,10).reshape(3,3)
print("Reshape do array \n", arr_reshape)

Reshape do array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
arr_random = np.random.rand(4,4)
print("Array random \n", arr_random)

Array random 
 [[0.9314261  0.05441206 0.75569615 0.3675607 ]
 [0.09858956 0.78493962 0.21907065 0.57926791]
 [0.17185009 0.03048949 0.04449163 0.63269249]
 [0.53602509 0.6425979  0.71903337 0.25611514]]
